development:
  adapter: postgresql
  encoding: utf8
  database: findthings_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: findthings_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: findthings_production
  pool: 5
  username: <%= ENV['FINDPATRIOTS_DATABASE_USER'] %>
  password: <%= ENV['FINDPATRIOTS_DATABASE_PASSWORD'] %>

